amadeus/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#Eu adicionei:
#from  django.conf.urls.defaults import patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
    #Eu adicionei:
    url(r'^$', 'core.views.user'),
    url(r'^cadastro/', include('core.urls', namespace='core')),
    #url(r'^cadastro/', include('users.urls')),

    # Examples:
    # url(r'^$', 'src.views.home', name='home'),
    # url(r'^src/', include('src.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

#quando estiver num ambiente de producao, retirar este bloco:
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

core/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('core.views',
    url(r'^$', 'user', name='user'),
    url(r'^(\d+)/sucesso/$', 'success', name='success'),
)

core/models.py
from django.db import models
from amadeus import settings

# Create your models here.

urlDefaultProfileImage = settings.STATIC_ROOT,'/assets/img/profile.png'

class User(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=16)
    email = models.EmailField(max_length=20, unique=True)
    #role = models.ForeignKey(Role)
    #cpf = models.CharField(max_length=11, unique=True)
    phone = models.CharField(max_length=8)
    sex = models.CharField(max_length=1)
    birthday = models.DateField(blank=True)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=2)
    formacaoPrincipal = models.CharField(max_length=100)
    anoFormacaoPrincipal = models.CharField(max_length=4)
    cursoFormacaoPrincipal = models.CharField(max_length=100)
    instituicaoFormacaoPrincipal = models.CharField(max_length=100)
    dadosCurriculares = models.CharField(max_length=300)
    createdAt = models.DateTimeField(auto_now_add=True)
    
    profileImage = models.FileField(upload_to='user/profileImages', default='user/profile.png', blank=True, null=True)
    

    def __unicode__(self):
        return self.name

core/forms.py
from django import forms
from models import User
from core.validators import UsernameValidator
from core.validators import PasswordValidator

FORMACAO_PRINCIPAL_CHOICES = (('Ensino Superior Completo', 'Ensino Superior Completo'),
                                                        ('Ensino Superior em andamento', 'Ensino Superior em andamento'),
                                                        ('Pos-Graduacao Completa', 'Pos-Graduacao Completa'),
                                                        ('Pos-Graduacao em andamento', 'Pos-Graduacao em andamento'),)

SEX_CHOICES = (('m','Masculino'),
                          ('f','Feminino'),)

STATE_CHOICES = (('AC','AC'),
                              ('AL','AL'),
                              ('AM','AM'),
                              ('AP','AP'),
                              ('PA','PA'),
                              ('PB','PB'),
                              ('PE','PE'),
                              ('RN','RN'),)

ANO_FORMACAO_CHOICES = (('1980','1980'),
                                                ('1981','1981'),
                                                ('1982','1982'),
                                                ('1983','1983'),)

class UserForm(forms.ModelForm):
    username = forms.CharField(validators=[UsernameValidator], max_length=16)
    password = forms.CharField(validators=[PasswordValidator], widget=forms.PasswordInput(), max_length=16)
    confirmPassword = forms.CharField(validators=[PasswordValidator], widget=forms.PasswordInput(), max_length=16)
    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=SEX_CHOICES)
    birthday = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'))
    state = forms.ChoiceField(widget=forms.Select, choices=STATE_CHOICES)
    formacaoPrincipal = forms.ChoiceField(widget=forms.Select, choices=FORMACAO_PRINCIPAL_CHOICES)
    anoFormacaoPrincipal = forms.ChoiceField(widget=forms.Select, choices=ANO_FORMACAO_CHOICES)

    class Meta:
        model = User

    def clean(self):
        super(UserForm, self).clean()

        if self.cleaned_data.get('password') != self.cleaned_data.get('confirmPassword'):
            raise forms.ValidationError('As senhas devem ser iguais.')
        return self.cleaned_data

core/views.py
# Create your views here.

from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings

from forms import UserForm
from models import User


def user(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            msg = u'Ola, %s, \n Seja bem vindo(a) ao Amadeus. Este e um email de confirmacao de cadastro. Confira todos os dados: \n\n Nome: %s \n Email: %s \n Data de Nascimento: %s' %  (user.name, user.name, user.email, user.birthday)

            send_mail(subject=u'Cadastro Realizado com Sucesso!',
                            message=msg,
                            from_email=settings.DEFAULT_FROM_EMAIL,
                            recipient_list=[user.email])
            return HttpResponseRedirect(reverse('core:success', args=[user.pk]))
    else:
        form = UserForm()

    context = RequestContext(request, {'form': form})
    return render_to_response('users/new.html', context)

def success(request, pk):
    usert = get_object_or_404(User, pk=pk)
    context = RequestContext(request, {'usert': usert}) #dentro das chaves esta havendo a declaracao de um bean e o RequestContext esta adicionando esse bean ao contexto.
    return render_to_response('users/success.html', context)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Amadeus</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}assets/css/bootstrap.css" rel="stylesheet">
    <!-- style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style-->
    <link href="{{ STATIC_URL }}assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}assets/css/amadeus.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ STATIC_URL }}assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  
  <body>
  
    <!-- div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Amadeus</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div--><!--/.nav-collapse -->
        <!-- /div>
      </div>
    </div -->

	<div class="top">
		<img src="{{ STATIC_URL }}assets/img/header.png" alt="Logotipo Amadeus" />
	</div>


   	<ul class="breadcrumb">
	  <li>
	    <a href="#">Inicio</a>
	  </li>
	  <li><img src="{{ STATIC_URL }}assets/img/breadcrumb-divider2.png" alt="" /></li>
	  <li class="active">Cadastro</li>
	</ul>

    <div class="container">

		<div class="content-leftColumn">
			<div style="margin-top: 30px; text-align: center;">
				<img src="{{ STATIC_URL }}assets/img/header.png" alt="Logotipo Amadeus" />
				<div>Crie uma nova conta Amadeus e entre nessa comunidade de Ensino a Distância.</div>
			</div>
			<div style="margin-top: 60px; text-align: center;">
				<img src="{{ STATIC_URL }}assets/img/android.png" alt="Logotipo Amadeus" />
				<div>Com uma conta no Amadeus você pode acessar os arquivos do seu curso através do seu computador, notebook ou celular.</div>
			</div>
			<div style="margin-top: 60px; text-align: center;">
				<img src="{{ STATIC_URL }}assets/img/download.png" alt="Logotipo Amadeus" />
				<div>Faça download e upload de aulas e arquivos através da sua conta no Amadeus.</div>
			</div>
		</div>

		<div class="content-centerRightColumn">
			{% block content %}
			{% endblock content %}
		</div>
		
    </div> <!-- /container -->

    <footer>
		<img class="top-logo" src="{{ STATIC_URL }}assets/img/footer.png" alt="Logotipo Amadeus" />
    	<ul>
		  <li>
		    <a href="#">Configuracoes</a> <span class="divider">|</span>
		  </li>
		  <li>
		    <a href="http://amadeus.cin.ufpe.br" target="#">O Projeto</a> <span class="divider">|</span>
		  </li>
		  <li>
		    <a href="http://www.cin.ufpe.br/~ccte/" target="#">Grupo CCTE</a>
		  </li>
		</ul>
    </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}assets/js/jquery.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-scrollspy.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

core/templates/footer.html

{% block footer %}

<ul class="breadcrumb">
  <li>
    <a href="#">Configuracoes</a> <span class="divider">/</span>
  </li>
  <li>
    <a href="#">O Projeto</a> <span class="divider">/</span>
  </li>
  <li>
    <a href="#">Grupo CCTE</a>
  </li>
</ul>

{% endblock footer %}

core/templates/users/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Cadastrar nova conta</h1>
    <form class="well" action="." enctype="multipart/form-data" method="POST">
        {% csrf_token %}
	    {{ form.non_field_errors }}
		    <div class="fieldWrapper">
		        <label for="id_name">Nome completo:</label>
		        {{ form.name }}
		        {{ form.name.errors }}
		    </div>
		    <div class="fieldWrapper">
		        <label for="id_email">Email:</label>
		        {{ form.email }}
		        {{ form.email.errors }}
		    </div>
	    	<hr />
		    <div class="fieldWrapper">
		        <label for="id_username">Login:</label>
		        {{ form.username }}
		        {{ form.username.errors }}
		    </div>
		    <div class="fieldWrapper">
		        <label for="id_password">Senha:</label>
		        {{ form.password }}
		        {{ form.password.errors }}
		    </div>
		    <div class="fieldWrapper">
		        <label for="id_confirmPassword">Confirmacao da Senha:</label>
		        {{ form.confirmPassword }}
		        {{ form.confirmPassword.errors }}
		    </div>
	    	<hr />
		    <div class="fieldWrapper">
		        <label for="id_birthday">Data de Nascimento:</label>
		        {{ form.birthday }}
		        {{ form.birthday.errors }}
		    </div>
		    <div class="fieldWrapper">
		        <label for="id_sex" class="labelForRadioGroup">Sexo:</label>
		        {{ form.sex }}
		        {{ form.sex.errors }}
		    </div>
	    	<hr />
	    	<div class="formBtnBar">
	        	<input style="text-align: right" class="btn btn-primary" type="submit" value="Confirmar">
        	</div>
    </form>
{% endblock content %}

core/templates/users/success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Usuario cadastrado com sucesso!</h1>
        <h3>{{ usert.name }},</h3>
        <p>Cadastro realizado em
        {{ usert.createdAt|date:"d/m/Y" }} as {{ usert.createdAt|date:"H:i:s" }}.
        </p>
        <img src="{{ MEDIA_URL }}{{ usert.profileImage }}" />
{% endblock content %}